AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  StockPriceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src-py/
      Handler: app.handler
      Runtime: python3.7
      Tracing: Active
      Events:
        StockAPIRequest:
          Type: Api
          Properties:
            Path: /
            Method: get
            RequestParameters:
              - method.request.querystring.ticker

Outputs:
  StockPrice:
    Description: "API Gateway endpoint URL for Prod stage for Stock Price function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
